# Site
name: "wireless hippie"
title: "wireless hippie"
description: "an online diary for a wireless hippie"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: https://wireless-hippie.github.io
google_analytics: 'G-ZFQES0QL2Y'
# disqus: 'https-wireless-hippie-github-io'
mailchimp-list: https://github.us7.list-manage.com/subscribe/post?u=67bc9a6384a973beca87db5fe&amp;id=15ec9c40ce
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mariana:
    name: mariana
    display_name: Mariana Meireles
    gravatar: 2de6c00a8f204bdf0b66f07697a334c1
    email: mariana@psychonaugirl.space
    web: https://psychonautgirl.space/about-me.html
    twitter: https://twitter.com/mari_meir
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
